ModalistBundle\Entity\WpOrders:
    type: entity
    table: wp_orders
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        numOrder:
            type: integer
            nullable: false
            unsigned: false
            column: num_order
        productsRef:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: products_ref
        buyerName:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: buyer_name
        buyerEmail:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: buyer_email
        shippingAddress:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: shipping_address
        shippingZipcode:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: shipping_zipcode
        shippingCity:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: shipping_city
        orderDate:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: order_date
        orderState:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: order_state
    lifecycleCallbacks: {  }
